version: '3.1'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_docker:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes: 
  postgres_docker:
